name: Contributor Helper

on:
  schedule: [{ cron: '0 18 * * *' }]
  workflow_dispatch:
jobs:
  contributor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions-cool/contributor-helper@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          style: 'simple'
          update-files: 'README.md'
          update-places: '<!-- CONTRIBUTION GROUP -->/<!-- CONTRIBUTION END -->'

      - name: Commit and push if changed
        run: |-
          git diff
          git config --global user.name "lobehubbot"
          git config --global user.email "i@lobehub.com"
          git pull
          git add -A
          git commit -m "🤖 docs: Auto update contributors" || exit 0
          git push
